// 1-100 are correct... 151 is correct.
export const pokeDescription: {} = {
    1:"There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    2:"When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
    3:"Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
    4:"It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    5:"It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.",
    6:"It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.",
    7:"When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    8:"It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.",
    9:"It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.",
    10:"For protection, it releases a horrible stench from the antenna on its head to drive away enemies.",
    11:"It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack.",
    12:"In battle, it flaps its wings at great speed to release highly toxic dust into the air.",
    13:"Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.",
    14:"Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.",
    15:"It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.",
    16:"Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.",
    17:"This Pokémon is full of vitality. It constantly flies around its large territory in search of prey.",
    18:"This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.",
    19:"Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area.",
    20:"Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.",
    21:"Inept at flying high. However, it can fly around very fast to protect its territory.",
    22:"A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.",
    23:"The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.",
    24:"The frightening patterns on its belly have been studied. Six variations have been confirmed.",
    25:"Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
    26:"Its long tail serves as a ground to protect itself from its own high-voltage power.",
    27:"It loves to bathe in the grit of dry, sandy areas. By sand bathing, the Pokémon rids itself of dirt and moisture clinging to its body.",
    28:"The drier the area Sandslash lives in, the harder and smoother the Pokémon’s spikes will feel when touched.",
    29:"Females are more sensitive to smells than males. While foraging, they’ll use their whiskers to check wind direction and stay downwind of predators.",
    30:"The horn on its head has atrophied. It’s thought that this happens so Nidorina’s children won’t get poked while their mother is feeding them.",
    31:"Nidoqueen is better at defense than offense. With scales like armor, this Pokémon will shield its children from any kind of attack",
    32:"The horn on a male Nidoran’s forehead contains a powerful poison. This is a very cautious Pokémon, always straining its large ears.",
    33:"With a horn that’s harder than diamond, this Pokémon goes around shattering boulders as it searches for a moon stone.",
    34:"When it goes on a rampage, it’s impossible to control. But in the presence of a Nidoqueen it’s lived with for a long time, Nidoking calms down.",
    35:"It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon.",
    36:"A timid fairy Pokémon that is rarely seen, it will run and hide the moment it senses people.",
    37:"While young, it has six gorgeous tails. When it grows, several new tails are sprouted.",
    38:"It is said to live 1,000 years, and each of its tails is loaded with supernatural powers.",
    39:"Jigglypuff has top-notch lung capacity, even by comparison to other Pokémon. It won’t stop singing its lullabies until its foes fall asleep.",
    40:"The more air it takes in, the more it inflates. If opponents catch it in a bad mood, it will inflate itself to an enormous size to intimidate them.",
    41:"It emits ultrasonic waves from its mouth to check its surroundings. Even in tight caves, Zubat flies around with skill.",
    42:"It loves to drink other creatures’ blood. It’s said that if it finds others of its kind going hungry, it sometimes shares the blood it’s gathered.",
    43:"If exposed to moonlight, it starts to move. It roams far and wide at night to scatter its seeds.",
    44:"Its pistils exude an incredibly foul odor. The horrid stench can cause fainting at a distance of 1.25 miles",
    45:"It has the world’s largest petals. With every step, the petals shake out heavy clouds of toxic pollen.",
    46:"Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition.",
    47:"The bug host is drained of energy by the mushroom on its back. The mushroom appears to do all the thinking.",
    48:"Its large eyes act as radar. In a bright place, you can see that they are clusters of many tiny eyes.",
    49:"The powdery scales on its wings are hard to remove from skin. They also contain poison that leaks out on contact.",
    50:"If a Diglett digs through a field, it leaves the soil perfectly tilled and ideal for planting crops.",
    51:"A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground.",
    52:"It loves to collect shiny things. If it’s in a good mood, it might even let its Trainer have a look at its hoard of treasures.",
    53:"Getting this prideful Pokémon to warm up to you takes a lot of effort, and it will claw at you the moment it gets annoyed.",
    54:"Psyduck is constantly beset by headaches. If the Pokémon lets its strange power erupt, apparently the pain subsides for a while",
    55:"This Pokémon lives in gently flowing rivers. It paddles through the water with its long limbs, putting its graceful swimming skills on display.",
    56:"An agile Pokémon that lives in trees. It angers easily and will not hesitate to attack anything.",
    57:"It stops being angry only when nobody else is around. To view this moment is very difficult.",
    58:"It has a brave and trustworthy nature. It fearlessly stands up to bigger and stronger foes.",
    59:"The sight of it running over 6,200 miles in a single day and night has captivated many people.",
    60:"For Poliwag, swimming is easier than walking. The swirl pattern on its belly is actually part of the Pokémon’s innards showing through the skin.",
    61:"Staring at the swirl on its belly causes drowsiness. This trait of Poliwhirl’s has been used in place of lullabies to get children to go to sleep.",
    62:"Its body is solid muscle. When swimming through cold seas, Poliwrath uses its impressive arms to smash through drift ice and plow forward.",
    63:"This Pokémon uses its psychic powers while it sleeps. The contents of Abra’s dreams affect the powers that the Pokémon wields.",
    64:"Using its psychic power, Kadabra levitates as it sleeps. It uses its springy tail as a pillow.",
    65:"It has an incredibly high level of intelligence. Some say that Alakazam remembers everything that ever happens to it, from birth till death.",
    66:"Its whole body is composed of muscles. Even though it’s the size of a human child, it can hurl 100 grown-ups.",
    67:"Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions.",
    68:"It quickly swings its four arms to rock its opponents with ceaseless punches and chops from all angles.",
    69:"Prefers hot and humid places. It ensnares tiny bugs with its vines and devours them.",
    70:"When hungry, it swallows anything that moves. Its hapless prey is dissolved by strong acids.",
    71:"Lures prey with the sweet aroma of honey. Swallowed whole, the prey is dissolved in a day, bones and all.",
    72:"Tentacool is not a particularly strong swimmer. It drifts across the surface of shallow seas as it searches for prey.",
    73:"When the red orbs on Tentacruel’s head glow brightly, watch out. The Pokémon is about to fire off a burst of ultrasonic waves.",
    74:"Commonly found near mountain trails and the like. If you step on one by accident, it gets angry.",
    75:"Often seen rolling down mountain trails. Obstacles are just things to roll straight over, not avoid.",
    76:"Once it sheds its skin, its body turns tender and whitish. Its hide hardens when it’s exposed to air.",
    77:"It can’t run properly when it’s newly born. As it races around with others of its kind, its legs grow stronger.",
    78:"This Pokémon can be seen galloping through fields at speeds of up to 150 mph, its fiery mane fluttering in the wind.",
    79:"Slow-witted and oblivious, this Pokémon won’t feel any pain if its tail gets eaten. It won’t notice when its tail grows back, either.",
    80:"Slowpoke became Slowbro when a Shellder bit on to its tail. Sweet flavors seeping from the tail make the Shellder feel as if its life is a dream.",
    81:"At times, Magnemite runs out of electricity and ends up on the ground. If you give batteries to a grounded Magnemite, it’ll start moving again.",
    82:"This Pokémon is three Magnemite that have linked together. Magneton sends out powerful radio waves to study its surroundings.",
    83:"The stalk this Pokémon carries in its wings serves as a sword to cut down opponents. In a dire situation, the stalk can also serve as food.",
    84:"Its short wings make flying difficult. Instead, this Pokémon runs at high speed on developed legs.",
    85:"One of Doduo’s two heads splits to form a unique species. It runs close to 40 mph in prairies.",
    86:"Loves freezing-cold conditions. Relishes swimming in a frigid climate of around 14 degrees Fahrenheit.",
    87:"Its entire body is a snowy white. Unharmed by even intense cold, it swims powerfully in icy waters.",
    88:"Made of congealed sludge. It smells too putrid to touch. Even weeds won’t grow in its path.",
    89:"Smells so awful, it can cause fainting. Through degeneration of its nose, it lost its sense of smell.",
    90:"It swims facing backward by opening and closing its two-piece shell. It is surprisingly fast.",
    91:"Its shell is extremely hard. It cannot be shattered, even with a bomb. The shell opens only when it is attacking.",
    92:"Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.",
    93:"Its tongue is made of gas. If licked, its victim starts shaking constantly until death eventually comes.",
    94:"On the night of a full moon, if shadows move on their own and laugh, it must be Gengar’s doing.",
    95:"As it digs through the ground, it absorbs many hard objects. This is what makes its body so solid.",
    96:"If you sleep by it all the time, it will sometimes show you dreams it had eaten in the past.",
    97:"Avoid eye contact if you come across one. It will try to put you to sleep by using its pendulum.",
    98:"It can be found near the sea. The large pincers grow back if they are torn out of their sockets.",
    99:"Its large and hard pincer has 10,000-horsepower strength. However, being so big, it is unwieldy to move.",
    100:"It is said to camouflage itself as a Poké Ball. It will self-destruct with very little stimulus.",

    101:"There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    102:"When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
    103:"Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
    104:"It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    105:"It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.",
    106:"It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.",
    107:"When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    108:"It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.",
    109:"It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.",
    110:"For protection, it releases a horrible stench from the antenna on its head to drive away enemies.",
    111:"It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack.",
    112:"In battle, it flaps its wings at great speed to release highly toxic dust into the air.",
    113:"Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.",
    114:"Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.",
    115:"It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.",
    116:"Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.",
    117:"This Pokémon is full of vitality. It constantly flies around its large territory in search of prey.",
    118:"This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.",
    119:"Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area.",
    120:"Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.",
    121:"Inept at flying high. However, it can fly around very fast to protect its territory.",
    122:"A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.",
    123:"The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.",
    124:"The frightening patterns on its belly have been studied. Six variations have been confirmed.",
    125:"Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
    126:"Its long tail serves as a ground to protect itself from its own high-voltage power.",
    127:"It loves to bathe in the grit of dry, sandy areas. By sand bathing, the Pokémon rids itself of dirt and moisture clinging to its body.",
    128:"The drier the area Sandslash lives in, the harder and smoother the Pokémon’s spikes will feel when touched.",
    129:"Females are more sensitive to smells than males. While foraging, they’ll use their whiskers to check wind direction and stay downwind of predators.",
    130:"The horn on its head has atrophied. It’s thought that this happens so Nidorina’s children won’t get poked while their mother is feeding them.",
    131:"Nidoqueen is better at defense than offense. With scales like armor, this Pokémon will shield its children from any kind of attack",
    132:"The horn on a male Nidoran’s forehead contains a powerful poison. This is a very cautious Pokémon, always straining its large ears.",
    133:"With a horn that’s harder than diamond, this Pokémon goes around shattering boulders as it searches for a moon stone.",
    134:"When it goes on a rampage, it’s impossible to control. But in the presence of a Nidoqueen it’s lived with for a long time, Nidoking calms down.",
    135:"It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon.",
    136:"A timid fairy Pokémon that is rarely seen, it will run and hide the moment it senses people.",
    137:"While young, it has six gorgeous tails. When it grows, several new tails are sprouted.",
    138:"It is said to live 1,000 years, and each of its tails is loaded with supernatural powers.",
    139:"Jigglypuff has top-notch lung capacity, even by comparison to other Pokémon. It won’t stop singing its lullabies until its foes fall asleep.",
    140:"The more air it takes in, the more it inflates. If opponents catch it in a bad mood, it will inflate itself to an enormous size to intimidate them.",
    141:"It emits ultrasonic waves from its mouth to check its surroundings. Even in tight caves, Zubat flies around with skill.",
    142:"It loves to drink other creatures’ blood. It’s said that if it finds others of its kind going hungry, it sometimes shares the blood it’s gathered.",
    143:"If exposed to moonlight, it starts to move. It roams far and wide at night to scatter its seeds.",
    144:"Its pistils exude an incredibly foul odor. The horrid stench can cause fainting at a distance of 1.25 miles",
    145:"It has the world’s largest petals. With every step, the petals shake out heavy clouds of toxic pollen.",
    146:"Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition.",
    147:"The bug host is drained of energy by the mushroom on its back. The mushroom appears to do all the thinking.",
    148:"Its large eyes act as radar. In a bright place, you can see that they are clusters of many tiny eyes.",
    149:"The powdery scales on its wings are hard to remove from skin. They also contain poison that leaks out on contact.",
    150:"If a Diglett digs through a field, it leaves the soil perfectly tilled and ideal for planting crops.",

    151:"When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen."
  };